---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "my-book-api-ms-service"
  labels:
    app: "my-book-api-ms"
spec:
  ports:
  - protocol: "TCP"
    port: 3001
    targetPort: 3000
  selector:
    app: "my-book-api-ms"
  type: "LoadBalancer"

